### ISSUE TITLE
SOQL Queries Not Working

### ISSUE THREAD

**Issue by jgallinagh** [datasert/realfire#24] opened 2019-05-13 11:13 UTC
Hello, after the most recent release I'm having a ton of issues with the query editor running SOQL queries.  I'm using queries that I've used in the past and haven't had any issues, but now I am.  

For example

![image](https://user-images.githubusercontent.com/19307148/57617322-8cb3c000-754e-11e9-9cc3-673e5b6171a3.png)

**Comment by brsanthu** [comment] 2019-05-13 14:19
@jgallinagh thank you bringing this to attention. We are aware of the issue. The issue is in the logic that tries to auto select soql stmt if nothing is selected. We will release an update soon.

Meanwhile, please select all text and it should work as expected.

**Comment by datasert** [comment] 2019-05-16 05:24
Realfire 5.1 has been released with this issue fixed.

**Closed as completed by datasert** 2019-05-16 05:24 UTC
